#!/usr/bin/env python3
"""Writes the muscle map VectorDrawables into the app's resources.

    python3 tools/gen_muscle_drawables.py

Generated, not hand-written: musclemap.py is the only place the artwork exists, so the preview
sheet and the shipped resources cannot disagree. Re-run after changing the artwork and commit the
result - the XML is reviewed in diffs like any other file.

Two kinds of file come out, and they stay separate on purpose:

  muscle_body_front / muscle_body_back   the silhouette, drawn once
  muscle_<code> / muscle_group_<code>    only the highlighted region

so the screen can tint the two independently - a muted silhouette under an accent-coloured muscle -
which a single drawable with both colours baked in could not do, and which is what makes dark mode
free rather than a second set of files.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import musclemap as m

RES = os.path.join(HERE, "..", "android-app", "app", "src", "main", "res", "drawable")

HEADER = """<!--
  Generated by tools/gen_muscle_drawables.py from tools/musclemap.py - do not edit by hand.
  Drawn for this project; not traced from any other product or from a copyrighted plate.
  Painted white so the layout tints it from the theme.
-->
"""

TEMPLATE = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="50dp"
    android:height="120dp"
    android:viewportWidth="{w:g}"
    android:viewportHeight="{h:g}">
{body}</vector>
"""


def path(data, opacity=None):
    alpha = f'\n        android:fillAlpha="{opacity}"' if opacity else ""
    return (f'    <path\n'
            f'        android:fillColor="#FFFFFFFF"{alpha}\n'
            f'        android:pathData="{data}" />\n')


def stroke(data):
    return (f'    <path\n'
            f'        android:strokeColor="#FFFFFFFF"\n'
            f'        android:strokeWidth="1.6"\n'
            f'        android:strokeAlpha="0.55"\n'
            f'        android:strokeLineCap="round"\n'
            f'        android:pathData="{data}" />\n')


def mirrored(data):
    """The same path reflected about the figure's axis, as a group rather than a second drawing."""
    return (f'    <group\n'
            f'        android:pivotX="{m.VIEW_W / 2:g}"\n'
            f'        android:scaleX="-1">\n'
            f'    {path(data).rstrip()}\n'
            f'    </group>\n')


def write(name, body):
    destination = os.path.join(RES, f"{name}.xml")
    with open(destination, "w", encoding="utf-8") as handle:
        handle.write(TEMPLATE.format(header=HEADER, w=m.VIEW_W, h=m.VIEW_H, body=body))
    return destination


def resource_name(code, prefix="muscle_"):
    return prefix + code.replace(".", "_")


def main():
    os.makedirs(RES, exist_ok=True)
    written = 0

    for side, hint in (("front", m.FRONT_HINT), ("back", m.BACK_HINT)):
        body = "".join(path(p) for p in m.FRONT_BODY) + "".join(stroke(p) for p in hint)
        write(f"muscle_body_{side}", body)
        written += 1

    for code, (side, paths, paired) in sorted(m.REGIONS.items()):
        body = "".join(path(p) + (mirrored(p) if paired else "") for p in paths)
        write(resource_name(code), body)
        written += 1

    for code in sorted(m.GROUP_SIDE):
        side, paths, paired = m.group_region(code)
        body = "".join(path(p) + (mirrored(p) if is_paired else "")
                       for p, is_paired in zip(paths, paired))
        write(resource_name(code, "muscle_group_"), body)
        written += 1

    print(f"{written} drawables em {os.path.normpath(RES)}")


if __name__ == "__main__":
    main()
